name: social_assistance
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.5
  dio: ^5.0.0
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/sobre.png
    - assets/servicos.png
    - assets/contato.png
    - assets/banner.png
